name: the-environment
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - numpy
  - pandas
  - ipywidgets
  - ipyleaflet
  - shapely
  - pip
  - itables
  - pip:
    - --editable
    - ./local_module